### ISSUE TITLE
Database is down

### ISSUE THREAD

**Issue by ltvuong** [olivettigroup/synthesis-api#1]
Hi guys,

I am having trouble accessing the database, I believe it is down right now.

**Comment by eddotman** [comment]
Ah, yes. This is something that was spun up while I was still a student, and AFAIK this particular API is no longer actively maintained (or, to be precise, the publicly-facing hosting infrastructure that backs this API is no longer maintained).

That said -- you can get much newer and higher quality data from this page now as a direct download: https://www.synthesisproject.org/resources-2 

Hope that helps! CC @elsaolivetti for visibility as well.

**Comment by ltvuong** [comment]
Oh wow, that's great! Thank you!
